CREATE TABLE estudiante
(
ID INT (20) NOT NULL AUTO_INCREMENT,
NID VARCHAR (50) NOT NULL,
Nombre VARCHAR (50) NOT NULL,
Apellido VARCHAR (50) NOT NULL,
Email VARCHAR (50) NOT NULL,
foto LONGBLOB NOT NULL,  
CONSTRAINT pk_llave PRIMARY KEY(ID));

SELECT *FROM estudiante

TRUNCATE TABLE estudiante

DROP TABLE estudiante